### ISSUE TITLE
连接全部失效了

### ISSUE THREAD

**Issue by eromoe** [vpei/Free-Node-Merge#3]
RT

ipfs resolve -r /ipns/k51qzi5uqu5dlfnig6lej7l7aes2d5oed6a4435s08ccftne1hq09ac1bulz2f/clash.yaml: no link named "clash.yaml" under QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn

**Comment by vpei** [comment]
正在更新。
